title: ""
description: Rashmi Menon | Personal Website
theme: minima

header_pages:
  - index.md

nav_external_links:
  - title: Resume
    url: /resume.pdf
  - title: Email me
    url: mailto:rashmi.tmenon@gmail.com
